apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-app
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-app
    spec:
      containers:
      - image: ghcr.io/nakamasato/fastapi-sample:v1.0
        name: fastapi-sample
        envFrom:
          - configMapRef:
              name: sample-app
          - secretRef:
              name: sample-app
        resources: {}
status: {}
